{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "arb-ws.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.kalshiKeyPem }}
  kalshi-key.pem: {{ .Values.secret.kalshiKeyPem | b64enc }}
  {{- end }}
{{- end }}
